<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Abraxius.App.Android</RootNamespace>
    <AssemblyName>Abraxius.Android</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Abraxius.App/Abraxius.App.csproj" />
    <ProjectReference Include="../Abraxius.Platform/Abraxius.Platform.csproj" />
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
  </ItemGroup>
</Project>
