<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Abraxius.Scheduler.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Abraxius.Scheduler/Abraxius.Scheduler.csproj" />
    <ProjectReference Include="../../src/Abraxius.Core/Abraxius.Core.csproj" />
    <ProjectReference Include="../../src/Abraxius.Platform/Abraxius.Platform.csproj" />
    <ProjectReference Include="../../src/Abraxius.Protocol/Abraxius.Protocol.csproj" />
    <ProjectReference Include="../../src/Abraxius.Memory/Abraxius.Memory.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
