<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Abraxius.Evaluation</RootNamespace>
    <AssemblyName>Abraxius.Evaluation</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Abraxius.Core/Abraxius.Core.csproj" />
    <ProjectReference Include="../Abraxius.Protocol/Abraxius.Protocol.csproj" />
    <ProjectReference Include="../Abraxius.Platform/Abraxius.Platform.csproj" />
    <ProjectReference Include="../Abraxius.Scheduler/Abraxius.Scheduler.csproj" />
    <ProjectReference Include="../Abraxius.Security/Abraxius.Security.csproj" />
    <ProjectReference Include="../Abraxius.Artifacts/Abraxius.Artifacts.csproj" />
    <ProjectReference Include="../Abraxius.Axl/Abraxius.Axl.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
