<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Abraxius.Platform.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Abraxius.Platform/Abraxius.Platform.csproj" />
    <ProjectReference Include="../../src/Abraxius.Core/Abraxius.Core.csproj" />
    <ProjectReference Include="../../src/Abraxius.Protocol/Abraxius.Protocol.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
