<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Abraxius.Platform</RootNamespace>
    <AssemblyName>Abraxius.Platform</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Abraxius.Protocol/Abraxius.Protocol.csproj" />
    <ProjectReference Include="../Abraxius.Core/Abraxius.Core.csproj" />
  </ItemGroup>
</Project>
