<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Abraxius.Voice</RootNamespace>
    <AssemblyName>Abraxius.Voice</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Abraxius.Protocol/Abraxius.Protocol.csproj" />
    <ProjectReference Include="../Abraxius.Core/Abraxius.Core.csproj" />
    <ProjectReference Include="../Abraxius.Platform/Abraxius.Platform.csproj" />
    <ProjectReference Include="../Abraxius.Models/Abraxius.Models.csproj" />
  </ItemGroup>
</Project>
